version: 0.2
# REQUIRED ENVIRONMENT VARIABLES
# REPOSITORY         - 758085500738.dkr.ecr.us-west-2.amazonaws.com/spring-data-jpa
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Build started on `date`
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY:latest --file DockerFile .
      - docker tag $REPOSITORY:latest $REPOSITORY:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY:latest
      - docker push $REPOSITORY:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '{"Image":"%s:%s"}' $REPOSITORY $IMAGE_TAG > build.json
      - printf '[{"name":"spring-data-jpa","imageUri":"%s"}]' $REPOSITORY:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - build.json
    - service.yml
    - production.json
    - imagedefinitions.json