version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - TAG="$(echo $CODE_BUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_NAME="spring-data-jpa"
      - echo Build started on `date`
  build:
    commands:
      - docker build -t $IMAGE_NAME --file DockerFile .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
      - printf '{"Image":"%s:%s"}' $REPOSITORY $IMAGE_TAG > build.json
artifacts:
  files:
    - build.json
    - service.yml
    - production.json
  discard-paths: yes